name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependancies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Deploy
        uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete
          path: theme/
          remote_path: /var/www/html/wp-content/themes/memo/
          remote_host: ${{secrets.DEPLOY_URL}}
          remote_user: ${{secrets.DEPLOY_USER}}
          remote_key: ${{ secrets.DEPLOY_KEY }}
